### ISSUE TITLE
Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1

### ISSUE THREAD

**Issue by dverasqrz** [google/tsunami-security-scanner#11]
Dear all,

After installing and building succesfully, I executed the example Tsunami command for scanning 127.0.0.1, but I receive the following error message:

BUILD SUCCESSFUL in 3m 22s
14 actionable tasks: 14 executed

java -cp "tsunami-main-0.0.2-SNAPSHOT-cli.jar:/home/diego/tsunami/plugins/*" -Dtsunami.config.location=/home/diego/tsunami/tsunami.yaml com.google.tsunami.main.cli.TsunamiCli --ip-v4-target=127.0.0.1 --scan-results-local-output-format=JSON --scan-results-local-output-filename=/tmp/tsunami-result.json Jun 30, 2020 7:23:40 PM com.google.tsunami.main.cli.TsunamiCli main
INFO: Full classpath scan took 1.986 s
Jun 30, 2020 7:23:40 PM com.google.tsunami.common.config.ConfigModule configure
INFO: Found Tsunami config class: com.google.tsunami.plugins.detectors.credentials.ncrack.NcrackWeakCredentialDetectorConfigs
Jun 30, 2020 7:23:40 PM com.google.tsunami.common.config.ConfigModule configure
INFO: Found Tsunami config class: com.google.tsunami.plugins.portscan.nmap.NmapPortScannerConfigs
Jun 30, 2020 7:23:40 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.common.io.archiving.GoogleCloudStorageArchiver$Options
Jun 30, 2020 7:23:40 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.main.cli.ScanResultsArchiver$Options
Jun 30, 2020 7:23:40 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.main.cli.option.ScanTargetCliOptions
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/diego/tsunami/tsunami-main-0.0.2-SNAPSHOT-cli.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jun 30, 2020 7:23:40 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.credentials.ncrack.NcrackWeakCredentialDetector
Jun 30, 2020 7:23:40 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.credentials.ncrack.NcrackWeakCredentialDetector is registered.
Jun 30, 2020 7:23:40 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.hadoop.yarn.YarnExposedManagerApiDetector
Jun 30, 2020 7:23:40 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.hadoop.yarn.YarnExposedManagerApiDetector is registered.
Jun 30, 2020 7:23:40 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.jenkins.JenkinsExposedUiDetector
Jun 30, 2020 7:23:40 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.jenkins.JenkinsExposedUiDetector is registered.
Jun 30, 2020 7:23:40 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.jupyter.JupyterExposedUiDetector
Jun 30, 2020 7:23:40 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.jupyter.JupyterExposedUiDetector is registered.
Jun 30, 2020 7:23:40 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.wordpress.WordPressInstallPageDetector
Jun 30, 2020 7:23:40 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.wordpress.WordPressInstallPageDetector is registered.
Jun 30, 2020 7:23:40 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.portscan.nmap.NmapPortScanner
Jun 30, 2020 7:23:40 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.portscan.nmap.NmapPortScanner is registered.
Jun 30, 2020 7:23:40 PM com.google.tsunami.main.cli.TsunamiCli main
SEVERE: Exiting due to workflow execution exceptions.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for com.google.tsunami.plugins.detectors.credentials.ncrack.client.NcrackClient (with no qualifier annotation) was bound, and could not find an injectable constructor. Injectable classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.google.tsunami.plugins.detectors.credentials.ncrack.client.NcrackClient.class(NcrackClient.java:148)
  while locating com.google.inject.Provider<com.google.tsunami.plugins.detectors.credentials.ncrack.client.NcrackClient>
    for the 1st parameter of com.google.tsunami.plugins.detectors.credentials.ncrack.NcrackCredentialTester.<init>(NcrackCredentialTester.java:79)
  at com.google.tsunami.plugins.detectors.credentials.ncrack.NcrackWeakCredentialDetectorBootstrapModule.configurePlugin(NcrackWeakCredentialDetectorBootstrapModule.java:40) (via modules: com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule -> com.google.tsunami.plugin.PluginLoadingModule -> com.google.tsunami.plugins.detectors.credentials.ncrack.NcrackWeakCredentialDetectorBootstrapModule)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:161)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at com.google.tsunami.main.cli.TsunamiCli.main(TsunamiCli.java:135)

Thanks in advance

OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
Ncrack version 0.7

**Comment by magl0** [comment]
Can you please try the quick start script again to rebuild all the plugins? This should have been fixed by https://github.com/google/tsunami-security-scanner-plugins/commit/9474dea47503a72bf638c3d7c00e226627fbd6e8.

**Comment by dverasqrz** [comment]
Thank you for the reply. I rebuilt all the plugins but no success. So, I downgraded from java 11 to java 8, and some of the problems were solved. However, there is still an issue.

diego@servtestesvmware:~$ cd ~/tsunami && java -cp "tsunami-main-0.0.2-SNAPSHOT-cli.jar:/root/tsunami/plugins/*" -Dtsunami-config.location=/root/tsunami/tsunami.yaml com.google.tsunami.main.cli.TsunamiCli --ip-v4-target=127.0.0.1 --scan-results-local-output-format=JSON --scan-results-local-output-filename=/tmp/tsunami-output-39.json
Jun 30, 2020 8:34:31 PM com.google.tsunami.main.cli.TsunamiCli main
INFO: Full classpath scan took 2.141 s
Jun 30, 2020 8:34:31 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.common.io.archiving.GoogleCloudStorageArchiver$Options
Jun 30, 2020 8:34:31 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.main.cli.ScanResultsArchiver$Options
Jun 30, 2020 8:34:31 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.main.cli.option.ScanTargetCliOptions
Jun 30, 2020 8:34:32 PM com.google.tsunami.main.cli.TsunamiCli main
SEVERE: Exiting due to workflow execution exceptions.
com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for java.util.Map<com.google.tsunami.plugin.PluginDefinition, javax.inject.Provider<com.google.tsunami.plugin.TsunamiPlugin>> was bound.
  while locating java.util.Map<com.google.tsunami.plugin.PluginDefinition, javax.inject.Provider<com.google.tsunami.plugin.TsunamiPlugin>>
    for the 1st parameter of com.google.tsunami.plugin.PluginManager.<init>(PluginManager.java:41)
  while locating com.google.tsunami.plugin.PluginManager
    for the 1st parameter of com.google.tsunami.workflow.DefaultScanningWorkflow.<init>(DefaultScanningWorkflow.java:100)
  while locating com.google.tsunami.workflow.DefaultScanningWorkflow
    for the 1st parameter of com.google.tsunami.main.cli.TsunamiCli.<init>(TsunamiCli.java:62)
  while locating com.google.tsunami.main.cli.TsunamiCli

1 error
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1120)
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1078)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131)
        at com.google.tsunami.main.cli.TsunamiCli.main(TsunamiCli.java:137)

**Comment by kakumanivrn** [comment]
+1
@magl0 I am facing this issue as well. I used quick_install script and used following yaml for config:
```
plugins:
  google:
    port_scanner:
      nmap:
        nmap_binary_path: "/usr/local/bin/nmap"
        port_targets: "80,8080,15000-16000"
```

**Comment by kakumanivrn** [comment]
UPDATE: Mine was fixed by using full path `/Users/user/tsunami/plugins` of the plugins folder instead of shortcut `~/tsunami/plugins`. @magl0 Please update documentation for MacOS to use full path only.

@dverasqrz Looks like your user folder is `/home/diego` but you are using `/root` folder for plugins. Please check your plugins path properly and it might fix the issue.

**Comment by magl0** [comment]
@kakumanivrn Thanks for confirming! In theory the `quick_start.sh` script should printout a command with full path using the `HOME` env variable. But it worth document it in the README.

**Comment by thesimpleone** [comment]
I was having the same issue.  I went ahead and ran the quick start code again and it gave me the commands to run.  It finally worked this time.

Running Quick Start:
bash -c "$(curl -sfL https://raw.githubusercontent.com/google/tsunami-security-scanner/master/quick_start.sh)"

and it gave me the output:
cd /home/kali/tsunami && \
java -cp "tsunami-main-0.0.2-SNAPSHOT-cli.jar:/home/kali/tsunami/plugins/*" \
  -Dtsunami-config.location=/home/kali/tsunami/tsunami.yaml \
  com.google.tsunami.main.cli.TsunamiCli \
  --ip-v4-target=127.0.0.1 \
  --scan-results-local-output-format=JSON \
  --scan-results-local-output-filename=/tmp/tsunami-output.json
